{
 "title": "Xapp",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Connected Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RRC-Connected User Allocation Per Cell ID (ONOS)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum (onos_xappkpimon_rrc_conn_avg) by (cell_id)",
     "legendFormat": "{{cell_id}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RRC - Connection Max Per Cell ID ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "onos_xappkpimon_rrc_conn_max",
     "legendFormat": "{{cell_id}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RRC Connection Establishment (Per Cell ID)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "RRC Connection Establishment Attempts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "onos_xappkpimon_rrc_connestabatt_sum",
     "legendFormat": "{{cell_id}}"
    }
   ]
  },
  {
   "title": "RRC Connection Establishment Successful ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "onos_xappkpimon_rrc_connestabsucc_sum",
     "legendFormat": "{{cell_id}} "
    }
   ]
  },
  {
   "title": "RRC Connection Reestablishment (Per Cell ID )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Due to Handover Fail",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum (onos_xappkpimon_rrc_connreestabatt_hofail) by (cell_id)",
     "legendFormat": "{{cell_id}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Due to Other",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "onos_xappkpimon_rrc_connreestabatt_other",
     "legendFormat": "{{cell_id}}"
    }
   ]
  },
  {
   "title": "Due to Reconfiguration Fail",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "onos_xappkpimon_rrc_connreestabatt_reconfigfail",
     "legendFormat": "{{cell_id}}"
    }
   ]
  },
  {
   "title": "Total Sum (per Cell)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (onos_xappkpimon_rrc_connreestabatt_sum) by (cell_id)",
     "legendFormat": "{{cell_id}}"
    }
   ]
  }
 ]
}